# Generated by Django 5.1.7 on 2025-03-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_budget_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='montant',
            field=models.FloatField(),
        ),
    ]
