# Generated by Django 5.1.7 on 2025-04-13 15:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_budget_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('owner', 'category')},
        ),
    ]
